#!/usr/bin/env node
// summarize.mjs — enrich fresh articles via a FREE LLM and write articles.json.
//
// Summaries + talking points are generated by GitHub Models (free inference), called
// with the same GITHUB_TOKEN the Action already has — no separate API key, no cost.
// The provider is isolated in callModel() so it can be swapped later (see roadmap:
// pluggable summarizer comparing GitHub Models / Anthropic / Gemini / Groq).
//
//   GITHUB_TOKEN=… node pipeline/summarize.mjs <instance_id>
//
// This file exposes building blocks (prepareInstance / summarizeArticle / commitInstance)
// so update.mjs can cross-post a multi-level story across instances. Token: in GitHub
// Actions, the built-in GITHUB_TOKEN with `permissions: models: read`; locally a PAT with
// the "Models" read permission exported as GITHUB_TOKEN.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { fetchFreshArticles, loadInstance } from './fetch-articles.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROMPT_PATH = resolve(__dirname, 'prompts', 'summarize-and-extract.txt');
const EXEMPLARS_PATH = resolve(__dirname, 'prompts', 'EXEMPLARS.json');
const VOICE_GUIDE_PATH = resolve(__dirname, 'prompts', 'VOICE_GUIDE.md');
const MAX_ARTICLES = 200;
const MAX_FEWSHOT = 2; // curated exemplars prepended per call to anchor the voice
export const LEVELS = ['federal', 'provincial', 'municipal'];

export function loadTemplate() {
  return readFileSync(PROMPT_PATH, 'utf8');
}

// The permanent editorial standard, sent as the system message on every call.
// Optional like the exemplars: absent guide → no system message, behavior unchanged.
let _voiceGuide;
function loadVoiceGuide() {
  if (_voiceGuide !== undefined) return _voiceGuide;
  try {
    _voiceGuide = existsSync(VOICE_GUIDE_PATH) ? readFileSync(VOICE_GUIDE_PATH, 'utf8') : '';
  } catch {
    _voiceGuide = '';
  }
  return _voiceGuide;
}

// Curated per-instance gold-standard exemplars (prompts/EXEMPLARS.json). Optional:
// if the file is absent or malformed, few-shot is simply skipped and behavior is unchanged.
let _exemplars;
function loadExemplars() {
  if (_exemplars !== undefined) return _exemplars;
  try {
    _exemplars = existsSync(EXEMPLARS_PATH) ? JSON.parse(readFileSync(EXEMPLARS_PATH, 'utf8')) : {};
  } catch {
    _exemplars = {};
  }
  return _exemplars;
}

// --- provider (the only piece to swap for a different summarizer) -----------
const MODEL = 'openai/gpt-4o-mini'; // free on GitHub Models
const ENDPOINT = 'https://models.github.ai/inference/chat/completions';

export function modelToken() {
  return process.env.GITHUB_TOKEN || process.env.GH_TOKEN || process.env.MODELS_TOKEN || '';
}

async function callModel(messages, schema, { retries = 3 } = {}) {
  const token = modelToken();
  if (!token) throw new Error('No model token — set GITHUB_TOKEN (with models:read) or GH_TOKEN');
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(ENDPOINT, {
      method: 'POST',
      headers: { 'content-type': 'application/json', authorization: `Bearer ${token}` },
      body: JSON.stringify({
        model: MODEL,
        temperature: 0.2,
        max_tokens: 1200,
        messages,
        response_format: {
          type: 'json_schema',
          json_schema: { name: 'article_analysis', strict: true, schema },
        },
      }),
    });
    if ((res.status === 429 || res.status >= 500) && attempt < retries) {
      await res.body?.cancel().catch(() => {}); // don't leak the abandoned body's socket
      const wait = Number(res.headers.get('retry-after')) * 1000 || 2 ** attempt * 5000;
      await new Promise((r) => setTimeout(r, wait));
      continue;
    }
    if (!res.ok) throw new Error(`GitHub Models ${res.status}: ${(await res.text()).slice(0, 200)}`);
    const data = await res.json();
    const content = data.choices?.[0]?.message?.content;
    return content ? JSON.parse(content) : null;
  }
}

// --- prompt + schema --------------------------------------------------------
function buildPrompt(template, config, article) {
  return template
    .replaceAll('{{politician.name}}', config.politician.name)
    .replaceAll('{{politician.title}}', config.politician.title)
    .replaceAll('{{politician.jurisdiction}}', config.politician.jurisdiction)
    .replaceAll('{{topic_tags}}', config.topic_tags.join(', '))
    .replaceAll('{{article.title}}', article.title || '')
    .replaceAll('{{article.source_name}}', article.source_name || '')
    .replaceAll('{{article.source_url}}', article.source_url || '')
    .replaceAll('{{article.published_at}}', article.published_at || '')
    .replaceAll('{{article.body}}', article.body || '');
}

// Build few-shot user/assistant message pairs from the instance's curated exemplars.
// Each pair mirrors the exact live prompt: the article stub rendered through buildPrompt,
// answered by the gold-standard JSON output — so the model imitates the voice, not just the schema.
function buildFewShot(template, config) {
  const all = loadExemplars();
  const list = Array.isArray(all[config.instance_id]) ? all[config.instance_id] : [];
  const msgs = [];
  for (const ex of list.slice(0, MAX_FEWSHOT)) {
    if (!ex || !ex.output) continue;
    const stub = ex.article_stub || {};
    const article = {
      title: stub.title || '',
      source_name: stub.source_name || '',
      source_url: stub.source_url || '',
      published_at: stub.published_at || '',
      body: stub.body_excerpt || stub.body || '',
    };
    msgs.push({ role: 'user', content: buildPrompt(template, config, article) });
    // Exemplars are publish-worthy by construction; stamp the gate fields so few-shot
    // outputs match the live schema without editing the curated file.
    msgs.push({
      role: 'assistant',
      content: JSON.stringify({ ...ex.output, hold_for_review: false, hold_reason: '' }),
    });
  }
  return msgs;
}

// Strict JSON schema; tags constrained to the instance's topic_tags, levels to the three tiers.
function outputSchema(config) {
  return {
    type: 'object',
    additionalProperties: false,
    required: [
      'relevant', 'summary', 'tags', 'talking_points', 'suggested_ask', 'tone_note', 'levels',
      'hold_for_review', 'hold_reason',
    ],
    properties: {
      relevant: { type: 'boolean' },
      hold_for_review: { type: 'boolean' },
      hold_reason: { type: 'string' },
      summary: { type: 'string' },
      tags: { type: 'array', items: { type: 'string', enum: config.topic_tags } },
      talking_points: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['point', 'source_reference'],
          properties: { point: { type: 'string' }, source_reference: { type: 'string' } },
        },
      },
      suggested_ask: { type: 'string' },
      tone_note: { type: 'string' },
      levels: { type: 'array', items: { type: 'string', enum: LEVELS } },
    },
  };
}

export function validate(obj) {
  if (!obj || obj.relevant === false) return null;
  const ok =
    typeof obj.summary === 'string' &&
    obj.summary.length > 0 &&
    Array.isArray(obj.tags) &&
    Array.isArray(obj.talking_points) &&
    obj.talking_points.length >= 1 &&
    obj.talking_points.every((t) => t && typeof t.point === 'string') &&
    typeof obj.suggested_ask === 'string';
  return ok ? obj : null;
}

// Summarize one raw article (with .body) through one instance's lens.
// Returns the enriched article (incl. `levels`) or null if the model judges it
// not relevant to THIS official's accountability.
export async function summarizeArticle(template, config, article) {
  const guide = loadVoiceGuide();
  const parsed = await callModel(
    [
      ...(guide
        ? [{
            role: 'system',
            content:
              'You are OpenLine\'s summarize stage. The following voice guide is the permanent editorial standard for every output. Match it exactly.\n\n' +
              guide,
          }]
        : []),
      ...buildFewShot(template, config),
      { role: 'user', content: buildPrompt(template, config, article) },
    ],
    outputSchema(config),
  );
  const out = validate(parsed);
  if (!out) return null;
  return {
    id: article.id,
    title: article.title,
    source_name: article.source_name,
    source_url: article.source_url,
    published_at: article.published_at,
    fetched_at: new Date().toISOString(),
    summary: out.summary,
    tags: out.tags.slice(0, 4),
    talking_points: out.talking_points.slice(0, 5),
    suggested_ask: out.suggested_ask,
    tone_note: out.tone_note,
    levels: Array.isArray(out.levels) ? out.levels.filter((l) => LEVELS.includes(l)) : [],
    hold_for_review: out.hold_for_review === true,
    hold_reason: typeof out.hold_reason === 'string' ? out.hold_reason : '',
  };
}

// Keep newest MAX_ARTICLES; roll the rest into archive/YYYY-MM.json by published month.
export function trimAndArchive(dir, articles) {
  const sorted = articles
    .slice()
    .sort((a, b) => Date.parse(b.published_at || 0) - Date.parse(a.published_at || 0));
  const keep = sorted.slice(0, MAX_ARTICLES);
  const overflow = sorted.slice(MAX_ARTICLES);
  if (overflow.length) {
    const archiveDir = resolve(dir, 'archive');
    if (!existsSync(archiveDir)) mkdirSync(archiveDir, { recursive: true });
    const byMonth = {};
    for (const a of overflow) {
      const month = (a.published_at || 'undated').slice(0, 7);
      (byMonth[month] ||= []).push(a);
    }
    for (const [month, items] of Object.entries(byMonth)) {
      const file = resolve(archiveDir, `${month}.json`);
      const prior = existsSync(file) ? JSON.parse(readFileSync(file, 'utf8')) : { articles: [] };
      const seen = new Set(prior.articles.map((a) => a.id));
      prior.articles.push(...items.filter((a) => !seen.has(a.id)));
      writeFileSync(file, JSON.stringify(prior, null, 2) + '\n');
    }
  }
  return keep;
}

export async function prepareInstance(id) {
  const { dir, articlesPath, heldPath, config, existing, held } = loadInstance(id);
  const { fresh } = await fetchFreshArticles(id);
  return { id, config, dir, articlesPath, heldPath, existing, held, fresh };
}

// Record self-gated items in the instance's held registry (committed, not published).
// A human reviews these via the digest; pipeline/promote.mjs moves an approved item
// into the live feed, or deleting its entry makes it eligible for a fresh attempt.
export function commitHeld(prep, heldArticles) {
  if (!heldArticles.length) return { held: 0 };
  const byId = new Map();
  for (const a of [...heldArticles.map((x) => ({ ...x, held_at: new Date().toISOString() })), ...prep.held.articles]) {
    if (!byId.has(a.id)) byId.set(a.id, a);
  }
  writeFileSync(
    prep.heldPath,
    JSON.stringify({ instance_id: prep.id, articles: [...byId.values()] }, null, 2) + '\n',
  );
  return { held: heldArticles.length };
}

// Merge newly-summarized articles into the instance feed and write it.
export function commitInstance(prep, newArticles) {
  if (!newArticles.length) return { added: 0, total: prep.existing.articles.length };
  // The gate fields are pipeline-internal — don't ship them in the public feed.
  const cleaned = newArticles.map(({ hold_for_review, hold_reason, ...a }) => a);
  // de-dupe by id (a cross-posted article may also have matched this instance directly)
  const byId = new Map();
  for (const a of [...cleaned, ...prep.existing.articles]) if (!byId.has(a.id)) byId.set(a.id, a);
  const merged = trimAndArchive(prep.dir, [...byId.values()]);
  writeFileSync(
    prep.articlesPath,
    JSON.stringify({ instance_id: prep.id, last_updated: new Date().toISOString(), articles: merged }, null, 2) + '\n',
  );
  return { added: newArticles.length, total: merged.length };
}

// Single-instance path (CLI). update.mjs uses the building blocks above to cross-post.
export async function summarizeInstance(instanceId, { dryRun = false } = {}) {
  const prep = await prepareInstance(instanceId);
  if (!prep.fresh.length) return { added: 0 };
  if (dryRun) {
    console.log(`  [${instanceId}] dry run — would summarize ${prep.fresh.length} article(s)`);
    return { added: 0, dryRun: true, candidates: prep.fresh.length };
  }
  const template = loadTemplate();
  const newOnes = [];
  const heldOnes = [];
  for (const article of prep.fresh) {
    try {
      const enriched = await summarizeArticle(template, prep.config, article);
      if (!enriched) {
        console.log(`  [${instanceId}] – skipped (irrelevant): ${article.title}`);
      } else if (enriched.hold_for_review) {
        heldOnes.push(enriched);
        console.log(`  [${instanceId}] ⏸ held for review: ${article.title} — ${enriched.hold_reason}`);
      } else {
        newOnes.push(enriched);
        console.log(`  [${instanceId}] ✓ ${article.title}`);
      }
    } catch (err) {
      console.error(`  [${instanceId}] ✗ ${article.title} — ${err.message}`);
    }
  }
  commitHeld(prep, heldOnes);
  const r = commitInstance(prep, newOnes);
  return { ...r, held: heldOnes.length };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const id = process.argv[2] || 'calldoug';
  summarizeInstance(id, { dryRun: process.argv.includes('--dry-run') })
    .then((r) => console.log(`  [${id}] done:`, r))
    .catch((e) => {
      console.error(e);
      process.exit(1);
    });
}
